version: '3'

services:
  web:
    build:
      context: .docker/php
    networks:
      - backend
    depends_on:
      - db
    volumes:
      - .:/app:rw,cached
    ports:
      - 9050:80
    entrypoint: /docker-entrypoint.d/start.sh

  db:
    image: mysql:5
    networks:
      - backend
    volumes:
      - ./config/schema:/dumps:ro,cached
    environment:
      - DEBUG=false
      - MYSQL_USER=bookmark
      - MYSQL_PASSWORD=bookmark
      - MYSQL_DATABASE=bookmark
      - MYSQL_ROOT_PASSWORD=bookmark

networks:
  backend:
