App\Domain\Bookmark\Model\Bookmark:
    normalizationContext:
        groups: ['bookmark:read']
    operations:
        ApiPlatform\Metadata\GetCollection: ~
        ApiPlatform\Metadata\Get: ~
        ApiPlatform\Metadata\Patch:
            input: App\Application\UpdateBookmark\UpdateBookmarkInput
            processor: ApiPlatform\Symfony\Messenger\Processor
